### ISSUE TITLE
the image for ellen kai is some touhou character and other issues

### ISSUE THREAD

**Issue by Xinnoh** [KN1053/charasort#1]
this is touhou
![screen shot 2018-11-23 at 10 49 59 pm](https://user-images.githubusercontent.com/30382015/48949191-1f957980-ef72-11e8-8b2a-f3e9bf522922.png)

colorado has the wrong image

![screen shot 2018-11-23 at 11 14 52 pm](https://user-images.githubusercontent.com/30382015/48950301-a9931180-ef75-11e8-93ef-3d575e7934ce.png)

**Comment by KN1053** [comment]
fixed! thanks.
